using FollowerForge.ModManagers;

namespace FollowerForge.Tests;

public sealed class ActiveProfileDetectorTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "ff_profiles_" + Guid.NewGuid().ToString("N"));

    private string MakeProfile(string id, params string[] plugins)
    {
        var dir = Path.Combine(_root, id);
        Directory.CreateDirectory(dir);
        File.WriteAllLines(Path.Combine(dir, "plugins.txt"),
            new[] { "# Automatically generated by Vortex" }.Concat(plugins));
        return dir;
    }

    [Fact]
    public void Detect_ExactMatchWins()
    {
        MakeProfile("A", "*Skyrim.esm", "*Mod1.esp");
        MakeProfile("B", "*Skyrim.esm", "*Other.esp");
        var runtime = Path.Combine(_root, "runtime.txt");
        File.WriteAllLines(runtime, ["*Skyrim.esm", "*Mod1.esp"]);

        var warnings = new List<string>();
        var (id, _) = ActiveProfileDetector.Detect(_root, runtime, warnings);
        Assert.Equal("A", id);
    }

    [Fact]
    public void Detect_SameSetDifferentOrder_IsIdentified_NoAlarm()
    {
        MakeProfile("A", "*Skyrim.esm", "*Mod1.esp", "*Mod2.esp");
        var runtime = Path.Combine(_root, "runtime.txt");
        // Same set, different order — Vortex regenerated the file.
        File.WriteAllLines(runtime, ["*Mod2.esp", "*Skyrim.esm", "*Mod1.esp"]);

        var warnings = new List<string>();
        var (id, reason) = ActiveProfileDetector.Detect(_root, runtime, warnings);
        Assert.Equal("A", id);
        Assert.Contains("order differs", reason);
        Assert.Empty(warnings);
    }

    [Fact]
    public void Detect_NearMatch_WarnsAboutUndeployedChanges()
    {
        // 19 shared + 1 extra on the profile ⇒ ~95% Jaccard.
        var shared = Enumerable.Range(0, 19).Select(i => $"*Mod{i}.esp").ToArray();
        MakeProfile("A", shared.Append("*Extra.esp").ToArray());
        var runtime = Path.Combine(_root, "runtime.txt");
        File.WriteAllLines(runtime, shared);

        var warnings = new List<string>();
        var (id, _) = ActiveProfileDetector.Detect(_root, runtime, warnings);
        Assert.Equal("A", id);
        Assert.Contains(warnings, w => w.Contains("undeployed"));
    }

    public void Dispose()
    {
        if (Directory.Exists(_root)) Directory.Delete(_root, recursive: true);
    }
}
