using System.Text.Json;
using FollowerForge.Domain;
using FollowerForge.ModManagers;
using FollowerForge.SkyrimRecords;
using FollowerForge.Validation;
using Serilog;

namespace FollowerForge.BuildPipeline;

/// <summary>
/// Builds a shared follower asset hub: a light-master plugin (marker keyword) plus a shared
/// asset tree that multiple followers reference instead of each duplicating body/skin/hair.
/// </summary>
public sealed class HubBuilder(ILogger log)
{
    private static readonly JsonSerializerOptions Json = new()
    {
        WriteIndented = true,
        Converters = { new System.Text.Json.Serialization.JsonStringEnumConverter() },
    };

    public sealed record HubManifest(
        string HubName,
        string PluginName,
        string MarkerKeywordFormKey,
        string MarkerKeywordEditorId,
        IReadOnlyList<string> ProvidesAssetFolders,
        string GeneratedBy = "Follower Forge");

    public sealed record HubBuildResult(bool Success, string OutputDirectory, string PluginPath, ValidationReport Validation);

    /// <param name="assetFolders">Data-relative folders the hub reserves for shared assets.</param>
    public HubBuildResult Build(string hubName, EnvironmentSnapshot env, string workspaceRoot,
        IReadOnlyList<string>? assetFolders = null)
    {
        var guard = VortexDiscovery.CreateGuard(env);
        guard.EnsureWritable(workspaceRoot);

        var pluginName = $"{Sanitize(hubName)}.esm";
        var staging = Path.Combine(workspaceRoot, ".staging", "hub_" + Sanitize(hubName));
        var finalDir = Path.Combine(workspaceRoot, "hubs", Sanitize(hubName));
        if (Directory.Exists(staging)) Directory.Delete(staging, recursive: true);
        Directory.CreateDirectory(staging);

        var report = new ValidationReport();
        var compiler = new HubCompiler(log);
        var result = compiler.Compile(pluginName);

        var pluginPath = Path.Combine(staging, pluginName);
        new PluginWriter(log).Write(result.Mod, pluginPath);
        EspHeaderValidator.Validate(pluginPath, report, requireEsl: true);

        // Reserve shared-asset folders under a hub-specific prefix so followers can point at them.
        var folders = assetFolders ?? DefaultAssetFolders(hubName);
        foreach (var f in folders)
            Directory.CreateDirectory(Path.Combine(staging, f));

        var manifest = new HubManifest(
            hubName, pluginName, result.MarkerKeyword.ToString(), result.MarkerEditorId, folders);
        File.WriteAllText(Path.Combine(staging, "hub-manifest.json"), JsonSerializer.Serialize(manifest, Json));
        File.WriteAllText(Path.Combine(staging, "README.md"), BuildReadme(hubName, manifest));

        if (report.HasErrors)
        {
            log.Error("Hub {Hub} failed validation; not publishing.", hubName);
            return new HubBuildResult(false, staging, pluginPath, report);
        }

        if (Directory.Exists(finalDir)) Directory.Delete(finalDir, recursive: true);
        Directory.CreateDirectory(Path.GetDirectoryName(finalDir)!);
        Directory.Move(staging, finalDir);
        log.Information("Published hub {Hub} → {Dir}", hubName, finalDir);
        return new HubBuildResult(true, finalDir, Path.Combine(finalDir, pluginName), report);
    }

    private static IReadOnlyList<string> DefaultAssetFolders(string hubName)
    {
        var prefix = Sanitize(hubName);
        return
        [
            Path.Combine("meshes", prefix, "body"),
            Path.Combine("meshes", prefix, "hair"),
            Path.Combine("textures", prefix, "body"),
            Path.Combine("textures", prefix, "head"),
        ];
    }

    private static string BuildReadme(string hubName, HubManifest m)
    {
        return $"""
            # {hubName} — Follower Asset Hub

            This hub is a shared master for followers generated by Follower Forge. Install it once;
            every follower that lists it as a requirement reuses these assets instead of shipping
            their own copies.

            - Hub plugin: `{m.PluginName}` (light master)
            - Marker keyword: `{m.MarkerKeywordEditorId}` ({m.MarkerKeywordFormKey})

            Place shared body/skin/hair assets under:
            {string.Join("\n", m.ProvidesAssetFolders.Select(f => "  - " + f))}
            """;
    }

    private static string Sanitize(string name) =>
        new(name.Where(c => char.IsLetterOrDigit(c) || c is '_' or '-').ToArray());
}
