using System.Text;
using System.Text.RegularExpressions;
using FollowerForge.Domain;

namespace FollowerForge.BuildPipeline;

/// <summary>
/// Share-ready text next to a published follower: checklist, author-prefix notes, and an optional
/// RaceMenu Overlay (RSV) exclusion INI so packaged hair/skin paths are not stomped by RSV.
/// </summary>
public static class SharePackageDocuments
{
    private static readonly Regex SafePrefix = new("^[A-Za-z][A-Za-z0-9]{0,7}$", RegexOptions.Compiled);

    /// <summary>
    /// 1–8 character author prefix starting with a letter. Used for plugin names, EditorIDs, and
    /// own-hub texture folders. Returns null when empty (optional); throws when present but illegal.
    /// </summary>
    public static string? NormalizeAuthorPrefix(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return null;
        var trimmed = raw.Trim();
        if (!SafePrefix.IsMatch(trimmed))
            throw new ArgumentException(
                "Author prefix must be 1–8 characters, start with a letter, and use only letters/digits "
                + $"(got '{raw}'). Example: FF or Kara.");
        return trimmed;
    }

    public static string SuggestPluginName(string followerName, string? authorPrefix)
    {
        var safe = new string(followerName.Where(c => char.IsLetterOrDigit(c) || c is '_' or '-').ToArray());
        if (safe.Length == 0) safe = "Follower";
        var prefix = authorPrefix ?? "FF";
        return $"{prefix}_{safe}.esp";
    }

    public static void WriteAll(
        string publishedDir,
        FollowerProfile profile,
        IReadOnlyList<string> masters,
        HubAssetPackager.Result? hubResult)
    {
        File.WriteAllText(
            Path.Combine(publishedDir, "SHARE-CHECKLIST.txt"),
            BuildChecklist(profile, masters, hubResult));

        var rsv = BuildRsvExclusion(profile, hubResult);
        if (rsv is not null)
            File.WriteAllText(Path.Combine(publishedDir, "RSVexclude.ini"), rsv);
    }

    public static string BuildChecklist(
        FollowerProfile profile,
        IReadOnlyList<string> masters,
        HubAssetPackager.Result? hubResult)
    {
        var sb = new StringBuilder();
        sb.AppendLine("Follower Forge — share / install checklist");
        sb.AppendLine("==========================================");
        sb.AppendLine();
        sb.AppendLine($"Follower : {profile.Name}");
        sb.AppendLine($"Plugin   : {profile.PluginName}");
        sb.AppendLine($"Prefix   : {profile.EditorIdPrefix ?? profile.OwnHubPrefix ?? "(default FF_ style EditorIDs)"}");
        sb.AppendLine();
        sb.AppendLine("Install");
        sb.AppendLine("-------");
        sb.AppendLine("1. Install this whole folder (or the matching .zip) with Vortex or MO2.");
        sb.AppendLine("2. Enable the plugin. Leave masters enabled in load order.");
        sb.AppendLine("3. Deploy / run the game. Use test-in-game.txt for console checks.");
        sb.AppendLine();
        sb.AppendLine("Masters this build declared");
        sb.AppendLine("---------------------------");
        foreach (var m in masters)
            sb.AppendLine($"  - {m}");
        if (masters.Count == 0) sb.AppendLine("  (none beyond base game — see dependency-report.json)");
        sb.AppendLine();
        sb.AppendLine("Before you upload to Nexus");
        sb.AppendLine("--------------------------");
        sb.AppendLine("- You must have redistribution permission for every third-party mesh/texture");
        sb.AppendLine("  you package (own-hub / portable modes). Credit is not permission.");
        sb.AppendLine("- List hard requirements: High Poly Head, hair mods, body, voice packs, etc.");
        sb.AppendLine("- Include credits.md and this checklist or your own credits section.");
        sb.AppendLine("- If RSVexclude.ini is present, ship it so RaceMenu Overlays does not overwrite");
        sb.AppendLine("  the hair/skin paths this follower relies on.");
        sb.AppendLine("- Do not ship someone else's full mod as \"your\" follower without their terms.");
        sb.AppendLine();
        sb.AppendLine("Face notes");
        sb.AppendLine("----------");
        sb.AppendLine("- Flat face vs player: slider-only presets need sculpt + Export Head (see build report).");
        sb.AppendLine("- Black face: incomplete Export Head / missing head parts — re-export with every part showing.");
        sb.AppendLine("- SMP hair physics need FSMP (or equivalent) on the player's game; the HDPT record alone is not enough.");
        sb.AppendLine();
        if (hubResult is { Copied: > 0 })
        {
            sb.AppendLine($"Own-hub assets copied: {hubResult.Copied} file(s). Read permissions-declaration.md.");
            sb.AppendLine();
        }
        sb.AppendLine("Generated by Follower Forge. This file is documentation only.");
        return sb.ToString();
    }

    /// <summary>
    /// Minimal RSV exclusion for retargeted texture folders under textures\&lt;prefix&gt;\…
    /// Returns null when nothing was retargeted (reference mode does not need an exclusion).
    /// </summary>
    public static string? BuildRsvExclusion(FollowerProfile profile, HubAssetPackager.Result? hubResult)
    {
        var paths = new List<string>();
        if (hubResult is not null)
        {
            paths.AddRange(hubResult.Assets
                .Select(a => a.RetargetedTo)
                .Where(p => !string.IsNullOrWhiteSpace(p))
                .Select(p => p!.Replace('/', '\\'))
                .Where(p => p.StartsWith("textures\\", StringComparison.OrdinalIgnoreCase))
                .Select(p => Path.GetDirectoryName(p)!.Replace('\\', '/'))
                .Distinct(StringComparer.OrdinalIgnoreCase));
        }

        if (paths.Count == 0 && !string.IsNullOrWhiteSpace(profile.OwnHubPrefix))
            paths.Add($"textures/{profile.OwnHubPrefix}");
        if (paths.Count == 0) return null;
        paths = paths.OrderBy(p => p, StringComparer.OrdinalIgnoreCase).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("; RaceMenu Overlay / RSV exclusion — generated by Follower Forge");
        sb.AppendLine($"; Follower: {profile.Name}");
        sb.AppendLine("; Ship this next to the plugin so overlay tools leave these folders alone.");
        sb.AppendLine();
        sb.AppendLine("[Exclusion]");
        foreach (var p in paths)
            sb.AppendLine(p.TrimEnd('/') + "/");
        return sb.ToString();
    }
}
