using FollowerForge.ModManagers;
using Xunit;

namespace FollowerForge.Tests;

/// <summary>
/// Two reported failures: "FollowerForge only uses the default paths (no one has Steam on C:)"
/// and MO2 users whose mods are not found.
/// </summary>
public class PathDiscoveryTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "ff_paths_" + Guid.NewGuid().ToString("N"));

    [Fact]
    public void GameRoot_AcceptsAnExplicitPathOffDriveC()
    {
        var game = Path.Combine(_root, "D-drive", "SteamLibrary", "steamapps", "common", "Skyrim Special Edition");
        Directory.CreateDirectory(Path.Combine(game, "Data"));

        Assert.Equal(Path.GetFullPath(game), GameRootResolver.Find(game));
        Assert.True(GameRootResolver.HasData(game));
    }

    [Fact]
    public void GameRoot_RejectsAFolderWithNoData()
    {
        var empty = Path.Combine(_root, "not-skyrim");
        Directory.CreateDirectory(empty);

        Assert.False(GameRootResolver.HasData(empty));
        Assert.Null(GameRootResolver.Find(empty));
    }

    [Fact]
    public void Mo2ModList_DropsDisabledModsAndSeparators()
    {
        var list = Path.Combine(_root, "modlist.txt");
        Directory.CreateDirectory(_root);
        File.WriteAllLines(list,
        [
            "# This file was automatically generated by Mod Organizer.",
            "+FirstMod",
            "-DisabledMod",
            "+SecondMod",
            "-----------separator",
            "+ThirdMod",
        ]);

        var order = PluginLists.ParseMo2ModList(list);

        Assert.DoesNotContain("DisabledMod", order);              // '-' is disabled
        Assert.DoesNotContain(order, m => m.StartsWith("---"));   // separators are not folders
        Assert.Equal(["FirstMod", "SecondMod", "ThirdMod"], order);
    }

    public void Dispose()
    {
        if (Directory.Exists(_root)) Directory.Delete(_root, recursive: true);
    }
}
