using FollowerForge.ModManagers;

namespace FollowerForge.Tests;

public sealed class PluginListTests
{
    [Fact]
    public void ParsePluginsTxt_MarksEnabledAndDisabled()
    {
        var file = Path.GetTempFileName();
        try
        {
            File.WriteAllLines(file,
            [
                "# Automatically generated by Vortex",
                "*Skyrim.esm",
                "*Update.esm",
                "DisabledMod.esp",
                "",
                "*My Follower.esp",
            ]);

            var entries = PluginLists.ParsePluginsTxt(file);

            Assert.Equal(4, entries.Count);
            Assert.True(entries[0].Enabled);
            Assert.Equal("Skyrim.esm", entries[0].PluginFileName);
            Assert.False(entries[2].Enabled);
            Assert.Equal("DisabledMod.esp", entries[2].PluginFileName);
            Assert.Equal("My Follower.esp", entries[3].PluginFileName);
            Assert.True(entries[3].Enabled);
        }
        finally { File.Delete(file); }
    }

    [Fact]
    public void ParseLoadOrderTxt_KeepsOrderSkipsComments()
    {
        var file = Path.GetTempFileName();
        try
        {
            File.WriteAllLines(file, ["# header", "Skyrim.esm", "Update.esm", "", "Mod.esp"]);
            var order = PluginLists.ParseLoadOrderTxt(file);
            Assert.Equal(["Skyrim.esm", "Update.esm", "Mod.esp"], order);
        }
        finally { File.Delete(file); }
    }

    [Theory]
    [InlineData("Skyrim.esm", true)]
    [InlineData("ccbgssse002-exoticarrows.esl", true)]
    [InlineData("_ResourcePack.esl", true)]
    [InlineData("SomeRandomMod.esp", false)]
    public void IsImplicitlyEnabled_CoversBaseAndCcAndResourcePack(string name, bool expected)
        => Assert.Equal(expected, SkyrimRecords.LoadOrderBuilder.IsImplicitlyEnabled(name));
}
