using FollowerForge.BuildPipeline;
using FollowerForge.Domain;
using FollowerForge.ModManagers;

namespace FollowerForge.Tests;

public sealed class Mo2AndSharePackageTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(), "ff_mo2_" + Guid.NewGuid().ToString("N"));

    public Mo2AndSharePackageTests()
    {
        Directory.CreateDirectory(_root);
    }

    public void Dispose()
    {
        try { Directory.Delete(_root, recursive: true); } catch (IOException) { }
    }

    [Fact]
    public void ParseMo2ModList_KeepsEnabledLowestToHighest()
    {
        var path = Path.Combine(_root, "modlist.txt");
        File.WriteAllText(path, """
            # This file was automatically generated by Mod Organizer.
            -disabled_mod
            +FirstMod
            +SecondMod
            ----------separators-are-skipped----------
            +ThirdMod
            """);

        var mods = PluginLists.ParseMo2ModList(path);
        Assert.Equal(new[] { "FirstMod", "SecondMod", "ThirdMod" }, mods);
    }

    [Fact]
    public void Mo2PathResolver_LastModWinsForPlugins()
    {
        var game = Path.Combine(_root, "game");
        var data = Path.Combine(game, "Data");
        var mods = Path.Combine(_root, "mods");
        var low = Path.Combine(mods, "Low");
        var high = Path.Combine(mods, "High");
        Directory.CreateDirectory(data);
        Directory.CreateDirectory(low);
        Directory.CreateDirectory(high);
        File.WriteAllText(Path.Combine(low, "Demo.esp"), "low");
        File.WriteAllText(Path.Combine(high, "Demo.esp"), "high");

        var env = new EnvironmentSnapshot
        {
            Manager = ModManagerKind.Mo2,
            ManagerLabel = "Mod Organizer 2",
            GameRootPath = game,
            GameDataPath = data,
            PluginDataPath = Path.Combine(_root, "view"),
            InstancePath = _root,
            StagingPath = mods,
            ProfilesPath = Path.Combine(_root, "profiles"),
            RuntimePluginsTxtPath = Path.Combine(_root, "plugins.txt"),
            Mo2ModPriority = ["Low", "High"],
        };

        var resolved = Mo2PathResolver.ResolvePlugin(env, "Demo.esp");
        Assert.NotNull(resolved);
        Assert.Equal("high", File.ReadAllText(resolved!));
    }

    [Fact]
    public void AuthorPrefix_AcceptsShortAlphanumeric()
    {
        Assert.Equal("Kara", SharePackageDocuments.NormalizeAuthorPrefix("Kara"));
        Assert.Equal("FF", SharePackageDocuments.NormalizeAuthorPrefix(" FF "));
        Assert.Null(SharePackageDocuments.NormalizeAuthorPrefix(" "));
        Assert.Throws<ArgumentException>(() => SharePackageDocuments.NormalizeAuthorPrefix("12bad"));
        Assert.Throws<ArgumentException>(() => SharePackageDocuments.NormalizeAuthorPrefix("toolongname"));
    }

    [Fact]
    public void ShareChecklist_MentionsSmpAndFaceFailures()
    {
        var text = SharePackageDocuments.BuildChecklist(
            new FollowerProfile
            {
                Name = "Test",
                PluginName = "FF_Test.esp",
                Race = new RecordRef("013746:Skyrim.esm"),
                VoiceType = new RecordRef("013ADD:Skyrim.esm"),
                Class = new RecordRef("0131E6:Skyrim.esm"),
                Placement = new PlacementSpec(),
            },
            ["Skyrim.esm", "Update.esm"],
            hubResult: null);

        Assert.Contains("SMP hair", text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("Black face", text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("Flat face", text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("SHARE", text, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void RsvExclusion_EmittedForOwnHubPrefix()
    {
        var profile = new FollowerProfile
        {
            Name = "Test",
            PluginName = "FF_Test.esp",
            Race = new RecordRef("013746:Skyrim.esm"),
            VoiceType = new RecordRef("013ADD:Skyrim.esm"),
            Class = new RecordRef("0131E6:Skyrim.esm"),
            Placement = new PlacementSpec(),
            OwnHubPrefix = "Kara",
            Hub = HubMode.OwnHub,
        };
        var rsv = SharePackageDocuments.BuildRsvExclusion(profile, hubResult: null);
        // Without hub result retargets, OwnHubPrefix still seeds a folder line.
        Assert.NotNull(rsv);
        Assert.Contains("textures/Kara/", rsv, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Mo2PathResolver_UsesCustomOverwritePath()
    {
        var game = Path.Combine(_root, "game_ow");
        var data = Path.Combine(game, "Data");
        var mods = Path.Combine(_root, "mods_ow");
        var customOw = Path.Combine(_root, "custom_overwrite");
        Directory.CreateDirectory(data);
        Directory.CreateDirectory(mods);
        Directory.CreateDirectory(customOw);
        File.WriteAllText(Path.Combine(customOw, "FromOverwrite.esp"), "ow");

        var env = new EnvironmentSnapshot
        {
            Manager = ModManagerKind.Mo2,
            ManagerLabel = "Mod Organizer 2",
            GameRootPath = game,
            GameDataPath = data,
            PluginDataPath = Path.Combine(_root, "view_ow"),
            InstancePath = _root,
            StagingPath = mods,
            ProfilesPath = Path.Combine(_root, "profiles_ow"),
            RuntimePluginsTxtPath = Path.Combine(_root, "plugins_ow.txt"),
            Mo2ModPriority = [Mo2PathResolver.OverwriteToken],
            Mo2OverwritePath = customOw,
        };

        var resolved = Mo2PathResolver.ResolvePlugin(env, "FromOverwrite.esp");
        Assert.NotNull(resolved);
        Assert.Equal("ow", File.ReadAllText(resolved!));
        Assert.Equal(customOw, Mo2PathResolver.ResolveOverwriteDir(env));
    }

    [Fact]
    public void ManagerPreference_MarkerRoundTrips()
    {
        var dir = ManagerPreference.SettingsDirectory;
        var marker = ManagerPreference.PreferMo2MarkerPath;
        var had = File.Exists(marker);
        try
        {
            ManagerPreference.SetPreferMo2(false);
            // PreferMo2 may still be true if env FFORGE_PREFER_MO2 is set — only assert marker file.
            Assert.False(File.Exists(marker));
            ManagerPreference.SetPreferMo2(true);
            Assert.True(File.Exists(marker));
            ManagerPreference.SetPreferMo2(false);
            Assert.False(File.Exists(marker));
        }
        finally
        {
            if (had) ManagerPreference.SetPreferMo2(true);
            else ManagerPreference.SetPreferMo2(false);
        }
    }
}
